### ISSUE TITLE
Duplicated TestStringReference class

### ISSUE THREAD

**Issue by nemesisdesign** [gregmuellegger/django-sortedm2m#105]
It looks like there is a [duplicated TestStringReference class](https://github.com/gregmuellegger/django-sortedm2m/blob/master/sortedm2m_tests/test_field.py#L186-L192).

I think the piece of code I just linked is not being executed currently.

Possible solutions would be:

1. rename it
2. delete it

**Comment by rohithasrk** [comment]
Renaming would be better option IMO. As it runs the same tests on another model named 'Store',

**Comment by nemesisdesign** [comment]
@rohithasrk tried renaming it and it's good to go
