### ISSUE TITLE
In Admin: build_attrs() got an unexpected keyword argument

### ISSUE THREAD

**Issue by astarrh** [gregmuellegger/django-sortedm2m#107]
Python 3.6.1 - Django 1.11 - Windows 10 - Package version: 1.3.3

I'm not really sure what's going on, but whenever I try to open an object in my admin panel, I get the following error:

`TypeError at /admin/Events/event/17/change/
build_attrs() got an unexpected keyword argument 'name'`

Exception is located at:

`C:\Users\Adam\Envs\otherlane_2\lib\site-packages\sortedm2m\forms.py in build_attrs, line 35`

This is the start of the function. This last line seems to be the issue:

        def render(self, name, value, attrs=None, choices=()):
            if value is None: value = []
            has_id = attrs and 'id' in attrs
            final_attrs = self.build_attrs(attrs, name=name)

It seems CKEditor had a similar problem and had to undergo a revision:
https://github.com/django-ckeditor/django-ckeditor/pull/364/files

**Comment by PaulGregor** [comment]
Same here. Django 1.11 causes this.

**Comment by ljholish** [comment]
Ran into this same TypeError, too. Django 1.11, python 3.5, sortedm2m 1.3.3
Error during template rendering
/lib/python3.5/site-packages/django/contrib/admin/templates/admin/includes/fieldset.html, error at line 19

Traceback (partial):

lib/python3.5/site-packages/sortedm2m/forms.py in build_attrs
35.  build_attrs(attrs, **kwargs)

**Comment by PaulGregor** [comment]
I made a [pull request](https://github.com/gregmuellegger/django-sortedm2m/pull/108) that fixes this problem.

**Comment by jbharrell92** [comment]
I believe this was also addressed in #104 by @fdintino

Unfortunately we haven't heard back from @gregmuellegger about the issue or PR in question

**Comment by fdintino** [comment]
This is addressed by #104. I emailed @gregmuellegger a week ago and he responded that he's aware of the pull request and that, though he's busy, he'll look into it when he can.

**Comment by gregmuellegger** [comment]
Hey, thank you all for the reports, comments and contributions! I just merged #104 and released 1.4.0 including a fix for this. Can you please test and confirm that this also fixes this issue?

**Comment by astarrh** [comment]
Confirmed that this resolves the issue for me. Thank you kindly for your excellent work!
