### ISSUE TITLE
Django Migrations no longer work with Django 1.7.4

### ISSUE THREAD

**Issue by mkoistinen** [gregmuellegger/django-sortedm2m#43]
I have a simple model that uses latest PyPI release of SortedM2M. Django migrations work with Django 1.7.3, but not with Django 1.7.4. I'm pretty sure this is why: https://code.djangoproject.com/ticket/24104, or possibly this one: https://code.djangoproject.com/ticket/24135

**Comment by richardbarran** [comment]
Django-photogue - which depends on django-sortedm2m - is also broken with Django 1.7.4, but works fine with 1.7.3.
I must admit that I am a little bit frustrated by the Django 1.7 micro releases that break existing code... :-(

**Comment by gregmuellegger** [comment]
Thanks for the report @mkoistinen and for the useful hint @richardbarran !!
That made the fix pretty easy.

**Comment by mkoistinen** [comment]
Awesome! Thanks for the quick turn-around. Any chance this can be pushed to the official PyPI release?

**Comment by gregmuellegger** [comment]
The testing and documenting of the migrations operation is a release
blocker at the moment. See the change log. I'm not sure when I'm able to
handle them. Feel free to tackle if you want
Am 30.01.2015 12:18 schrieb "Martin Koistinen" <notifications@github.com>:
