### ISSUE TITLE
Unique over the three values

### ISSUE THREAD

**Issue by chrko** [gregmuellegger/django-sortedm2m#49]
In my current project I have the problem that I want the unique index over the three columns `(from_, to, field.sort_value_field_name)` in generated through model which is currently specified fix: [53322c4a[…]/sortedm2m/fields.py#L74](https://github.com/gregmuellegger/django-sortedm2m/blob/5322c4a8a7680d60f6cbe6401d2bf7953273abd8/sortedm2m/fields.py#L74)

What should I do in this case?

Should be there an option `three_column_unique`?

**Comment by gregmuellegger** [comment]
I pushed something in the branch `feature/customizable-intermediate-model`. It
pulls the creation of the through model into the Field class and provides a
hook in the form of ``get_intermediate_model_attributes``. I think it should
be possible with this hook to implement your custom unique_together with
something like this:

```python
class MySortedM2M(SortedManyToManyField):
    def get_intermediate_model_attributes(self, attrs):
        attrs['Meta'].unique_together = (
            (attrs['_sort_field_name'], attrs['_to_field_name'], attrs['_from_field_name'],),
        )
        return attrs
```

Then use your custom field their and it should work well then.
Please give that a try and report back if that works for you. I'm happy to
merge these changes into master once you confirm that it solves your usecase.

**Comment by chrko** [comment]
Currently `feature/customizable-intermediate-model` is even with `master`?

**Comment by gregmuellegger** [comment]
Oops, I didn't push. Sorry! Should be there now.

**Comment by chrko** [comment]
Yes, this works. Thanks!

**Comment by gregmuellegger** [comment]
I did a new refactor of the model creation. So the example from above won't work any more as it had with the branch. However you can now hook into the `get_intermediate_model_meta_class()` method to accomplish your usecase.

I'm curious what you think of the refactor in https://github.com/gregmuellegger/django-sortedm2m/commit/a66b9ac52c3450507c07b6ece752f056b67dab80

**Comment by chrko** [comment]
I like the way to intercept the creation of the through model with hooks as of overiding some small methods.
And if you have now forgotten any corner case, the first step is done. :+1:
