### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by wengole** [gregmuellegger/django-sortedm2m#64]
Just took 1.9b1 for a spin, and immediately get this trying to start my app using SortedManyToManyField

```
File ".../sortedm2m/fields.py", line 8, in <module>
    from django.db.models.fields.related import add_lazy_relation, create_many_related_manager
```
Looks like create_many_related_manager has been removed, but I can't find explicit reference to this in the release notes.

**Comment by sodds** [comment]
`create_many_related_manager` was moved to `django/db/models/fields/related_descriptors.py` in https://github.com/django/django/commit/005c9fc45f99d03344fa9fae3dd984c2ab87f1ea

**Comment by nemesisdesign** [comment]
This fix https://github.com/shvechikov/django-sortedm2m/commit/8dff963483025aa9db08bd7b8f5ed53638406756 seems to work for me. Pheraphs you could cherry-pick it?

**Comment by gregmuellegger** [comment]
We already should have Django 1.9 in master with the merge of #65. @nemesisdesign is master working for you with Django 1.9?

**Comment by nemesisdesign** [comment]
@gregmuellegger sorry for not answering.. i'm drowning in github notifications here and I miss the good ones :-1: 

Thanks for releasing Django 1.9 support :+1:
