### ISSUE TITLE
Push Django 1.9 support to PyPI

### ISSUE THREAD

**Issue by outime** [gregmuellegger/django-sortedm2m#69]
Django 1.9 [has been released](https://www.djangoproject.com/weblog/2015/dec/01/django-19-released/) and django-sortedm2m package [at PyPI](https://pypi.python.org/pypi/django-sortedm2m) doesn't have support for it.

**Comment by gregmuellegger** [comment]
Fixed :) https://pypi.python.org/pypi/django-sortedm2m
I just released 1.1.0

**Comment by outime** [comment]
Thank you!
