### ISSUE TITLE
South's --auto doesn't work for ManyToManyField -> SortedManyToManyField

### ISSUE THREAD

**Issue by akaihola** [gregmuellegger/django-sortedm2m#7]
If I have a `Poll` model with a `questions = models.ManyToManyField(Question)`, and I change the field into a SortedManyToManyField, South doesn't detect the change:

    $ ./manage.py schemamigration --auto polls
    Nothing seems to have changed.

This is Django pre-1.5, django-sortedm2m 0.4.0 and South 0.7.6.

**Comment by rolandgeider** [comment]
@gorandev What is the status for this? Is there something I could help you with?

**Comment by gorandev** [comment]
@rolandgeider I have to document it and add some tests! Can you help with that? :)

**Comment by rolandgeider** [comment]
@gorandev I can do the documentation, not sure about the tests.

**Comment by rolandgeider** [comment]
I have opened a pull request (#42) with my first attempt at documenting this, feedback welcome

**Comment by outime** [comment]
How's this going?

**Comment by rolandgeider** [comment]
@outime I have started working on the tests [on my branch](https://github.com/rolandgeider/django-sortedm2m/commits/datamigration), but they are not ready yet

**Comment by gregmuellegger** [comment]
Thanks @rolandgeider for making a good start on this! I finished of the work and added tests for the `AlterSortedManyToManyField` operation. The operation has been released as part of the 0.9.0 release: https://pypi.python.org/pypi/django-sortedm2m/

**Comment by rolandgeider** [comment]
Cool, thanks!

**Comment by gorandev** [comment]
+1

**Comment by georgedorn** [comment]
I tried @akaihola's approach for getting a south migration to add sort_value, but while the migration isn't reporting an error the column doesn't appear to exist after the migration runs.

**Comment by gregmuellegger** [comment]
@georgedorn could you paste the forwards and backwards method of your migration here so that we can see what you have by now?
