### ISSUE TITLE
collectstatic with S3BotoStorage

### ISSUE THREAD

**Issue by erm0l0v** [gregmuellegger/django-sortedm2m#71]
Hi Guys. 

I have problem with **collectstatic** command.

I use `S3BotoStorage` with `ManifestFilesMixin` as a static files storage and I got an error after run **collectstatic**.

https://github.com/gregmuellegger/django-sortedm2m/blob/1.1.1/sortedm2m/forms.py#L28

`static` function tries to get file from S3, but it impossible until **collectstatic** will be done.

**Comment by gregmuellegger** [comment]
Yep, that makes sense. Thanks. I didn't know that the URL will be prefixed with the STATIC_URL setting :)
