### ISSUE TITLE
Checkbox not displayed when using jet dashboard

### ISSUE THREAD

**Issue by alexandrenorman** [gregmuellegger/django-sortedm2m#73]
When used with jet dashboard (http://jet.geex-arts.com/), 
checkbox are not displayed in admin. This prevents user to select fields.

Correction proposal for templates/sortedm2m/sorted_checkbox_select_multiple_widget.html:

```
11c11
<         <li><label{{ row.label_for|safe }}>{{ row.rendered_cb }} {{ row.option_label }}</label></li>

---
>         <li>{{ row.rendered_cb }} <label{{ row.label_for|safe }}>{{ row.option_label }}</label></li>
15c15
<         <li><label{{ row.label_for|safe }}>{{ row.rendered_cb }} {{ row.option_label }}</label></li>

---
>         <li>{{ row.rendered_cb }} <label{{ row.label_for|safe }}>{{ row.option_label }}</label></li
```

This way, it works. Did not see any drawback.

**Comment by gregmuellegger** [comment]
Hm, I'm not convinced with this method. I like having the input inside the label. Maybe a CSS change might fit better here.
