### ISSUE TITLE
Access to sort_value column value 

### ISSUE THREAD

**Issue by cheluis** [gregmuellegger/django-sortedm2m#74]
Greetings, I am trying to use sorted to order some questions inside a quiz, so far I have these two models:

```
class Quiz(models.Models):
    text = models.CharField(max_length=255)
    questions = SortedManyToManyField("Question")

class Question(models.Model):
    text = models.CharField(max_length=255)
    .
    .
    .
```

In my views I need to get the sorted_value column value but its not accessible. Question object has not sorted_value property. I used to have a property called "order", I removed but the migration created kept the field. But when I reorder questions inside admin,  the value which is changed is sort_value. I need to access this sort_value.

**Comment by gregmuellegger** [comment]
Hi, I think sortedm2m is not the right choice for your scenario. It is meant as a transparent replacement to Django's ManyToManyField.

Is a `Question` specific to one `Quiz`? In that case, you should use a `ForeignKey(Quiz)` on the Question model and add a order field there.

If a question might be part of multiple quizzes, then you would create an intermediary model like this one:

```python
class Quiz(models.Models):
    text = models.CharField(max_length=255)
    questions = SortedManyToManyField("Question", through="QuizQuestion")

class Question(models.Model):
    text = models.CharField(max_length=255)

class QuizQuestion(models.Model):
    quiz = models.ForeignKey(Quiz)
    question = models.ForeignKey(Question)
    order = models.IntegerField()
    class Meta:
        ordering = ('order',)
```

That way you have total access to the ordering field and how questions will be ordered in the frontend.

**Comment by cheluis** [comment]
Thanks for your response.
