### ISSUE TITLE
Regression in 1.3

### ISSUE THREAD

**Issue by czpython** [gregmuellegger/django-sortedm2m#80]
Hello,
I'm getting a ``TypeError NoneType object is not iterable`` when saving an object in the admin.
I think it's related to the line above where the check for None was removed.
https://github.com/gregmuellegger/django-sortedm2m/commit/428a8a85c0e7fad42e6d89db4d3a0ab10a508017#commitcomment-17613670

**Comment by vqw** [comment]
@czpython @vxsx 
+1 for this, exactly the same issue driving me crazy in DjangoCMS

**Comment by qdotme** [comment]
@czpython @vxsx @vqw 
+1 Ditto on DjangoCMS. Any workarounds?

**Comment by vqw** [comment]
@qdotme Hi Tomek, best is to install
django-sortedm2m==1.2.2

For the moment it works.
Cheers,
Marcin

**Comment by gregmuellegger** [comment]
Hi, sorry for breaking it! This slipped through the review for the last release. This will get fixed soonish with #83

**Comment by gregmuellegger** [comment]
Just released 1.3.2, containing a fix for this issue. Thanks to @NinjaDero for the fix.
https://pypi.python.org/pypi/django-sortedm2m
