### ISSUE TITLE
Thumbnails in admin template?

### ISSUE THREAD

**Issue by NathanielHill** [gregmuellegger/django-sortedm2m#84]
Is there a simple way to display thumbnails in the admin interface? I've set __str__() to return an anchor tag with appropriate href (as I've done in the rest of admin), but it gets escaped by your template. This seems like an important feature, since dragging and dropping a list of filenames is far from optimal in the case of a photo gallery.

**Comment by gregmuellegger** [comment]
True, however the best approach here might be to implement your own widget
and use it in the admin. In that case you get absolute control over what
you display and how.

**Comment by NathanielHill** [comment]
For anyone that comes across this, I solved my problem by using format_html() like so:

def __str__(self):
   return format_html(u'<img src="{}" width="100" height="100"/>', self.image.url)

**Comment by NathanielHill** [comment]
@tritone11 I solved this by not using Python for the last two years :rofl: Sorry, can't help you :man_shrugging:

**Comment by tritone11** [comment]
> @tritone11 I solved this by not using Python for the last two years  Sorry, can't help you
Thanks anyway :)
