### ISSUE TITLE
Widget not diplaying properly in forms.

### ISSUE THREAD

**Issue by kashsingh** [gregmuellegger/django-sortedm2m#85]
Hey, I am quite new to Django and was trying to implement the sortedm2m widget in my forms. The code I used is

> class TrackForm(forms.ModelForm):
>     title = forms.CharField(max_length=128, help_text="Please enter the track title.")
>     views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
>     genres = SortedMultipleChoiceField(queryset=Genre.objects.all())

but I got this. It is plain list of labels without the scroller, also multiple objects cannot be added only one of the selected object is added to the Trackform data. I am thinking, it may be due failing widget.

![screenshot from 2016-07-10 15 54 48](https://cloud.githubusercontent.com/assets/12440889/16713002/e6d0a3f6-46b6-11e6-9d81-2cfd7fdb7d6c.png)

**Comment by gregmuellegger** [comment]
Hi, sorry for not responding to this properly. Did you manage to fix the problem for you?

I'm closing this issue for now as it is quite old. Feel free to reopen it if you still have a problem getting it to work.
