### ISSUE TITLE
Silent failure when adding duplicate items

### ISSUE THREAD

**Issue by nhammond** [gregmuellegger/django-sortedm2m#86]
Adding a duplicate of the same model instance to a SortedManyToMany relationship silently fails.

Intuitively, I can understand how unordered Django ManyToMany fields behave as a Set and do not allow duplicates. But for an ordered relationship, I would expect it to behave like a List, and dropping duplicates is counterintuitive.

Are there any known workarounds, or do you know of any other tools better suited for implementing list/queue/stack behavior where duplicates are allowed?

```
# models.py

from django.db import models
from sortedm2m.fields import SortedManyToManyField

class Task(models.Model):
    name = models.CharField(max_length=255)

class Routine(models.Model):
    tasks = SortedManyToManyField('Task')
```

```
# usage:
sleep = Task(name='sleep')
sleep.save()
        
eat = Task(name='eat')
eat.save()
        
work =Task(name='work')
work.save()

routine = Routine()
routine.save()
        
 routine.tasks.add(eat)   # 1
 routine.tasks.add(work) # 2
 routine.tasks.add(eat)    # 3 = duplicate of 1
 routine.tasks.add(sleep) # 4

 routine.tasks.count() # returns 3
```

**Comment by gregmuellegger** [comment]
Yes, as you suspect it's not supported by Django's m2m field. That's also the reason why sortedm2m won't support it.

You can always fall back to implement your own model for the relation and use it as `through` model. Like:

```
class RoutineTask(models.Model):
  task = models.ForeignKey(Task)
  routine = models.ForeignKey('Routine', related_name='routine_tasks')
  sort_value = models.IntegerField()
```

You won't be able to use the hand `routine.task.add()` helper, but you need to create the `RoutineTask` instances by hand.
