### ISSUE TITLE
Missing javascript method html_unescape. 

### ISSUE THREAD

**Issue by Tipuch** [gregmuellegger/django-sortedm2m#91]
When adding an element to a sortedm2m field through the admin (through a popup).
When saving the instance the popup doesn't close, and there is this single error in the javascript console:
ReferenceError: html_unescape is not defined  (widget.js:91:17).
It apparently can't find the html_unescape javascript function for some reason. 

tested with Django1.10.3, django-sortedm2m==1.3.2

`if (window.showAddAnotherPopup) {
            var django_dismissAddAnotherPopup = window[dismissPopupFnName];
            window[dismissPopupFnName] = function (win, newId, newRepr) {
                // newId and newRepr are expected to have previously been escaped by
                // django.utils.html.escape.
                newId = html_unescape(newId);`

**Comment by Tipuch** [comment]
The javascript function was removed from django in this commit (if that can help.)

https://github.com/django/django/commit/cbaa3ee3ee45d453ab6aa36d57847515dd130b9f

**Comment by gregmuellegger** [comment]
Hey, thanks for the report. Do you have any suggestions on how to fix it? I'm happy for any PR on this topic, so if you are interested, feel free to hack on it.

**Comment by Tipuch** [comment]
https://github.com/gregmuellegger/django-sortedm2m/pull/92

**Comment by unloder** [comment]
My project also needs this, please merge as soon as possible.

**Comment by gregmuellegger** [comment]
merged

**Comment by gregmuellegger** [comment]
https://pypi.python.org/pypi/django-sortedm2m new version 1.3.3 released
